name: third workflow
on: push
jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
           - name: Validate html files
             run: test -f index.html



    bye-job:
        runs-on: ubuntu-latest
        steps:
            - name: validate js files
              run: test -f script.js
              